version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: appdbpost
    ports:
      - 5432:5432
